### PR TITLE
Events on player joining/leaving group

### LINKED ISSUE #697: Add cancellable event when player joining/leaving group
`PlayerQuests.ReceiveLeaveGroupRequest` method for patching can be used

### PR DESCRIPTION
**Pull request by DevInc0**
Closes #697

### CODE REVIEW

**Review by Trojaner — APPROVED** [review]

**Comment by rube200** [comment]
For Group leave request patch GroupManager.requestGroupExit instead

**Comment by rube200** [comment]
Also PlayerQuests.ReceiveGroupState can not be cancelled and it also can contain CSteamId.Nil equivalent of leaving a group

**Review by rube200 — CHANGES_REQUESTED** [review]
Check PR comment about harmony patches

**Comment by DevInc0** [comment]
> Also PlayerQuests.ReceiveGroupState can not be cancelled and it also can contain CSteamId.Nil equivalent of leaving a group

Investigated source code more careful and came up with a question. Is it even possible to cancel player joining a group? Seems like there's no way to do this.

**Comment by rube200** [comment]
In case of leave group you need to patch this method and copy that logic part
image

In case of join/change group you need to batch both methods (dont forget the logic for the second one)

image

image

**Review by rube200 — APPROVED** [review]

**Comment by rube200** [comment]
@DevInc0 can you test my lasts changes, i think this is ready to pr

**Comment by DevInc0** [comment]
@rube200 Everything works fine on my local server, but I believe there's no need in those event handlers:

```cs
private void OnGroupRankChanged(PlayerQuests sender, EPlayerGroupRank oldGroupRank, EPlayerGroupRank newGroupRank)
{
    var player = GetUnturnedPlayer(sender.player)!;

    var @event = new UnturnedPlayerGroupRankChangedEvent(player, oldGroupRank, newGroupRank);

    Emit(@event);
}

private void OnGroupIdChanged(PlayerQuests sender, CSteamID oldGroupId, CSteamID newGroupId)
{
    var player = GetUnturnedPlayer(sender.player)!;

    var @event = new UnturnedPlayerGroupIdChangedEvent(player, oldGroupId, newGroupId);

    Emit(@event);
}
```

Since there's already an event which we use:
```cs
// PlayerQuests.cs

/// <summary>
/// Event for plugins when group or rank changes.
/// </summary>
public static event PlayerQuests.GroupChangedCallback onGroupChanged;
```
```cs
public override void Subscribe()
{
    PlayerQuests.onGroupChanged += OnGroupOrRankChanged;
    // ...
}

public override void Unsubscribe()
{
    PlayerQuests.onGroupChanged -= OnGroupOrRankChanged;
    // ...
}
```

Instead we could implement `OnGroupRankChanged` and `OnGroupRankChanged` like this:

```cs
private void OnGroupOrRankChanged(PlayerQuests sender, CSteamID oldGroupId, EPlayerGroupRank oldGroupRank, CSteamID newGroupId, EPlayerGroupRank newGroupRank)
{
    var player = GetUnturnedPlayer(sender.player)!;

    if (oldGroupRank != newGroupRank)
    {
        var groupRankChangedEvent = new UnturnedPlayerGroupRankChangedEvent(player, oldGroupRank, newGroupRank);

        Emit(groupRankChangedEvent);
    }

    if (newGroupId != oldGroupId)
    {
        var groupIdChangedEvent = new UnturnedPlayerGroupIdChangedEvent(player, oldGroupId, newGroupId);

        Emit(groupIdChangedEvent);
    }

    var groupIdOrRankChangedEvent = new UnturnedPlayerGroupOrRankChangedEvent(player, oldGroupId, oldGroupRank, newGroupId, newGroupRank);

    Emit(groupIdOrRankChangedEvent);
}
```

Because anyways those events will be called from this method:
```cs
[SteamCall(ESteamCallValidation.ONLY_FROM_SERVER, legacyName = "tellSetGroup")]
public void ReceiveGroupState(CSteamID newGroupID, EPlayerGroupRank newGroupRank)
{
    CSteamID groupID = this.groupID;
    this.groupID = newGroupID;
    EPlayerGroupRank groupRank = this.groupRank;
    this.groupRank = newGroupRank;
    if (groupID != newGroupID)
    {
        this.triggerGroupIDChanged(groupID, newGroupID); // UnturnedPlayerGroupIdChangedEvent
    }
    if (groupRank != this.groupRank)
    {
        this.triggerGroupRankChanged(groupRank, this.groupRank); // UnturnedPlayerGroupRankChangedEvent
    }
    PlayerQuests.triggerGroupUpdated(this);
    PlayerQuests.broadcastGroupChanged(this, groupID, groupRank, newGroupID, this.groupRank); // UnturnedPlayerGroupOrRankChangedEvent
}
```

What do you think about this idea?

**Comment by rube200** [comment]
Yeh sure, I just added it since it was missing but we can change to data, and hope Nelson doesn't change anything

**Comment by Trojaner** [comment]
Is this ready for merge?

**Comment by DevInc0** [comment]
> Is this ready for merge?

Yes, it's ready. Last commit works fine

**Pull request merged**
