### PR TITLE
Use non-obsolete method to spawn vehicle

### PR DESCRIPTION
**Pull request by CyberAndrii**

### CODE REVIEW

**Comment by CyberAndrii** [comment]
> Are you sure? It doesn’t seem to make sense that it would have the same parameters yet have a different symbol.

It has a different return type.

**Comment by archie426** [comment]
Does it return InteractableVehicle?

**Comment by rube200** [comment]
It does

**Comment by Trojaner** [comment]
Please replace VehicleManager.vehicles.Last() with the returned value in that case

**Pull request merged**
