### PR TITLE
Add command to reload roles

### PR DESCRIPTION
**Pull request by DiFFoZ**

### CODE REVIEW

**Comment by Trojaner** [comment]
There should be no need to reload permissions: OpenMod should instantly apply any changes to the roles or players file

**Comment by aviadmini** [comment]
OM 2.2.2 doesn't reload permissions from `openmod.roles.yaml` automatically. `/om reload` works

**Comment by rube200** [comment]
this is cause by file watcher not working

**Comment by Trojaner** [comment]
we need to rewrite file watcher so it watches the directory instead

**Pull request closed without merging**
