### PR TITLE
Update some patches to the Unturned netcode update

### LINKED ISSUE #438: Prepare for Unturned net code updates
Currently some events rely on patched methods which may become obsolete in upcoming Unturned patches.

### PR DESCRIPTION
**Pull request by DiFFoZ**
Closes #438

### CODE REVIEW

**Comment by Trojaner** [comment]
askEnterVehicle is obsolete now, we should replace it too

**Review by Trojaner — CHANGES_REQUESTED** [review]
Builds are failing

**Comment by IAmSilK** [comment]
New preview binaries are needed for the build

**Comment by DiFFoZ** [comment]
I'll update Unturned redist when Nelson adds an alternative method for `VehicleManager.askEnterVehicle`

**Pull request merged**
