### PR TITLE
Added UiEffectsKeysProvider

### PR DESCRIPTION
**Pull request by aviadmini**

### CODE REVIEW

**Comment by Trojaner** [comment]
Please use IOpenModComponent instead of IOpenModPlugin so its more abstract

**Comment by aviadmini** [comment]
> Please use IOpenModComponent instead of IOpenModPlugin so its more abstract
> Also auto unrelease on plugin unload

I don't have a way of tracking the unloading of `IOpenModComponent`

**Comment by IAmSilK** [comment]
`IOpenModComponent.LifetimeScope.CurrentScopeEnding` may work for this purpose.

**Comment by aviadmini** [comment]
I'm not sure it's even needed, smh I doubt anything but plugins is gonna generate effect keys

Let's talk in discord once I take a look at that

**Pull request merged**
