### PR TITLE
Fixes when libs are missing

### PR DESCRIPTION
**Pull request by rube200**
Fixes for issue #112

### CODE REVIEW

**Comment by Trojaner** [comment]
This is not the correct way to do it. A plugin may work completely without issues even if some types do not load, e.g. when it has optional dependencies.

**Comment by rube200** [comment]
The problem is currently is not working with required dependencies,
I test it with my economy plugin

**Comment by rube200** [comment]
Btw auto patching plugins with Harmony is throwing exceptions if optional dependencies are not found

**Comment by Trojaner** [comment]
> Btw auto patching plugins with Harmony is throwing exceptions if optional dependencies are not found
Sounds like an issue that should be reported to Harmony. Can you post the exception please?

I will review this PR again and do the required changes manually.

**Comment by rube200** [comment]
Ok so changes to `PluginAssemblyStore.cs` only affect when a required lib is missing,
so i reverte this file `PluginActivator.cs `:

```
Loading plugins...
[My.Plugin1] [loading] Plugin1 v1.0.1
[My.Plugin2] Failed to load plugin from type: My.Plugin2.Plugin2 in assembly: My.Plugin2, Version=1.0.1.0, Culture=neutral, PublicKeyToken=null
System.Reflection.ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
  at (wrapper managed-to-native) System.Reflection.Assembly.GetTypes(System.Reflection.Assembly,bool)
  at System.Reflection.Assembly.GetTypes () [0x00000] in <e1319b7195c343e79b385cd3aa43f5dc>:0
  at System.Reflection.Assembly+<get_DefinedTypes>d__150.MoveNext () [0x0001e] in <e1319b7195c343e79b385cd3aa43f5dc>:0
  at System.Linq.Enumerable+SelectEnumerableIterator`2[TSource,TResult].MoveNext () [0x00029] in <fbb5ed17eb6e46c680000f8910ebb50c>:0
  at System.Linq.Enumerable+WhereEnumerableIterator`1[TSource].ToList () [0x00030] in <fbb5ed17eb6e46c680000f8910ebb50c>:0
  at System.Linq.Enumerable.ToList[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x0001f] in <fbb5ed17eb6e46c680000f8910ebb50c>:0
  at OpenMod.Core.Ioc.ServiceRegistrationHelper+<FindFromAssembly>d__0`1[T].MoveNext () [0x0004e] in <459c196869b74a60a2a5f9c81b6729b1>:0
  at System.Collections.Generic.EnumerableHelpers.ToArray[T] (System.Collections.Generic.IEnumerable`1[T] source, System.Int32& length) [0x00032] in <fbb5ed17eb6e46c680000f8910ebb50c>:0
  at System.Linq.Buffer`1[TElement]..ctor (System.Collections.Generic.IEnumerable`1[T] source) [0x00022] in <fbb5ed17eb6e46c680000f8910ebb50c>:0
  at System.Linq.OrderedEnumerable`1+<GetEnumerator>d__3[TElement].MoveNext () [0x0001e] in <fbb5ed17eb6e46c680000f8910ebb50c>:0
  at OpenMod.Core.Plugins.PluginActivator+<>c__DisplayClass10_0.<TryActivatePluginAsync>b__0 (Autofac.ContainerBuilder containerBuilder) [0x00271] in <459c196869b74a60a2a5f9c81b6729b1>:0
  at Autofac.Core.Lifetime.LifetimeScope.CreateScopeRestrictedRegistry (System.Object tag, System.Action`1[T] configurationAction) [0x000ad] in <0e43922c38cb4505ab27fe9ce1207b2d>:0
  at Autofac.Core.Lifetime.LifetimeScope.BeginLifetimeScope (System.Object tag, System.Action`1[T] configurationAction) [0x0001b] in <0e43922c38cb4505ab27fe9ce1207b2d>:0
  at Autofac.Core.Lifetime.LifetimeScope.BeginLifetimeScope (System.Action`1[T] configurationAction) [0x00007] in <0e43922c38cb4505ab27fe9ce1207b2d>:0
  at OpenMod.Core.Plugins.PluginActivator+<TryActivatePluginAsync>d__10.MoveNext () [0x00117] in <459c196869b74a60a2a5f9c81b6729b1>:0
```

when i supress this on
this happens: 

```
Loading plugins...
[My.Plugin1] [loading] Plugin1 v1.0.1
[My.Plugin2] [loading] Plugin2 v1.0.1
[OpenMod.Core.Plugins.PluginActivator] Failed to load plugin: Plugin2 v1.0.1
System.Reflection.ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
  at (wrapper managed-to-native) System.Reflection.Assembly.GetTypes(System.Reflection.Assembly,bool)
  at System.Reflection.Assembly.GetTypes () [0x00000] in <e1319b7195c343e79b385cd3aa43f5dc>:0
  at HarmonyLib.Harmony.PatchAll (System.Reflection.Assembly assembly) [0x00000] in <e1f1ac2cbe0f4a33bf2c833b6962b66e>:0
  at OpenMod.Core.Plugins.OpenModPluginBase.LoadAsync () [0x00087] in <c63fc57bb8d04308b06e33e906e03e6f>:0
  at OpenMod.Core.Plugins.OpenModUniversalPlugin.LoadAsync () [0x00000] in <c63fc57bb8d04308b06e33e906e03e6f>:0
  at OpenMod.Core.Plugins.PluginActivator+<TryActivatePluginAsync>d__10.MoveNext () [0x0018e] in <c63fc57bb8d04308b06e33e906e03e6f>:0
[12:39:10 INF][OpenMod.Runtime.OpenModHostedService] > 1 plugins loaded.
```

**Comment by rube200** [comment]
Outdated, a newer version is being prepared

**Pull request closed without merging**
