### PR TITLE
Fix module detection

### PR DESCRIPTION
**Pull request by rube200**
Sadly i didn't test

### CODE REVIEW

**Comment by rube200** [comment]
I tested with this last commit and the problem is solved

**Comment by Trojaner** [comment]
Build is failing

**Comment by DiFFoZ** [comment]
need fix this
https://github.com/openmod/openmod/blob/ffa6e0e1b2b3b65b1e009339e95905a0dd337cc3/framework/OpenMod.Bootstrapper/OpenModDynamicBootstrapper.cs#L57-L58

**Comment by rube200** [comment]
Build fixed

**Pull request merged**
