### PR TITLE
Cache NuGet package identity

### PR DESCRIPTION
**Pull request by DiFFoZ**
By caching, we can improve start up time by ~80%.

| Before | After |
|--------|--------|
| img | img | 

Still need some testing to make sure new bugs are not introduced.

This is the diff of how I'm testing performance:
```diff
diff --git a/standalone/OpenMod.Standalone/Program.cs b/standalone/OpenMod.Standalone/Program.cs
index d6752ae4..3b9f10a6 100644
--- a/standalone/OpenMod.Standalone/Program.cs
+++ b/standalone/OpenMod.Standalone/Program.cs
@@ -1,11 +1,12 @@
 ﻿using System;
-using System.IO;
-using System.Threading.Tasks;
 using System.Collections.Generic;
-using OpenMod.API;
+using System.IO;
 using System.Reflection;
+using System.Threading.Tasks;
 using Microsoft.Extensions.DependencyInjection;
-using Microsoft.Extensions.Hosting;
+using OpenMod.API;
+using OpenMod.Core.Plugins.NuGet;
+using OpenMod.NuGet;

 namespace OpenMod.Standalone
 {
@@ -17,20 +18,58 @@ namespace OpenMod.Standalone

             var path = Path.Combine(AppContext.BaseDirectory, "openmod");
             var runtime = new Runtime.Runtime();
+
+            var packagesDirectory = Path.Combine(path, "packages");
+            if (!Directory.Exists(packagesDirectory))
+            {
+                Directory.CreateDirectory(packagesDirectory);
+            }
+
+            var nugetPackageManager = new NuGetPackageManager(packagesDirectory)
+            { Logger = new NuGetConsoleLogger() };
+
+            // these dependencies are not required and cause issues
+            nugetPackageManager.IgnoreDependencies(
+                "Microsoft.NETCore.Platforms",
+                "Microsoft.Packaging.Tools",
+                "NETStandard.Library",
+                "OpenMod.UnityEngine.Redist",
+                "OpenMod.Unturned.Redist",
+                "System.IO.FileSystem.Watcher");
+
+            foreach (var package in new[] { "OpenMod.UnityEngine", "OpenMod.Unturned" })
+            {
+                var installedPackage = await nugetPackageManager.GetLatestPackageIdentityAsync(package);
+                if (installedPackage == null)
+                {
+                    var packageSearch = await nugetPackageManager.QueryPackageExactAsync(package);
+                    var searchedPackage = packageSearch?.Identity;
+                    if (searchedPackage == null)
+                    {
+                        continue;
+                    }
+
+                    if (installedPackage == null || searchedPackage.Version > installedPackage.Version)
+                    {
+                        var result = await nugetPackageManager.InstallAsync(searchedPackage);
+                        installedPackage = result.Identity!;
+                    }
+                }
+
+                var npgFile = nugetPackageManager.GetNugetPackageFile(installedPackage);
+                await nugetPackageManager.LoadAssembliesFromNuGetPackageAsync(npgFile);
+            }
+
             var host = await runtime.InitAsync(new List<Assembly> { typeof(Program).Assembly }, new RuntimeInitParameters
             {
                 CommandlineArgs = args,
-                WorkingDirectory = path
+                WorkingDirectory = path,
+                PackageManager = nugetPackageManager
             });

-            var applifecycle = host.Services.GetRequiredService<IHostApplicationLifetime>();
-            applifecycle.ApplicationStopping.Register(StandaloneConsoleIo.StopListening);
-
-            var autoCompletionHandler = host.Services.GetRequiredService<IAutoCompleteHandler>();
-            ReadLine.AutoCompletionHandler = autoCompletionHandler;
-            ReadLine.HistoryEnabled = true;
-
-            StandaloneConsoleIo.StartListening();
+            // uncomment to test installing of package
+            // var nugetSource = host.Services.GetRequiredService<NuGetPluginAssembliesSource>();
+            // await nugetSource.InstallPackageAsync("OpenMod.Economy");
         }
     }
-}
+}
```

### CODE REVIEW

**Comment by rube200** [comment]
what about iinstalling new packages?

**Comment by DiFFoZ** [comment]
From my testing - no diff (or is very small).

**Comment by Trojaner** [comment]
Nice 👍

**Comment by DiFFoZ** [comment]
It's now ready for testing. If some users want to test the start-up time, dm me in discord, I will give you the modified version of OpenMod module.

**Comment by DiFFoZ** [comment]
@negrifelipe and I tested this PR on locally, works without any errors 😊.

Waiting for review and merge!

**Review by Trojaner — APPROVED** [review]

**Pull request merged**
