### PR TITLE
Change Permssion from lowest to normal

### PR DESCRIPTION
**Pull request by rube200**

### CODE REVIEW

**Comment by rube200** [comment]
Dont merge yet

**Comment by Trojaner** [comment]
What is this change for?

**Comment by rube200** [comment]
Changing priority will allow plugins to create their own service implementation and enforce them.
When priority is lowest, om will always setup default at first.
Being with normal priority it will let devs to decide if they want lowest or highest priority

**Comment by rube200** [comment]
The second commit will fix a bug where OM returns the default roleStore instead of rmStore.

**Pull request merged**
